FROM debian:stable-slim

ARG REPOSITORY=gohugoio/hugo
ARG VERSION=0.92.1
ARG FILE_SHA256SUM=8368f13403b176d79fa7196b557a91e77246f16f3073e0826af90a42933e8d6e
ENV FILE_URL https://github.com/${REPOSITORY}/releases/download/v${VERSION}/hugo_${VERSION}_Linux-64bit.tar.gz
